-- Atualiza micro-região das cidades já cadastradas
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Álvaro de Carvalho' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Alvinlândia' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Duartina' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Fernão' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Gália' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Garça' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Herculândia' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Júlio Mesquita' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Lupércio' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Marília' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Ocauçu' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Oriente' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Pompéia' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Quintana' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Tupã' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Ubirajara' AND state = 'SP';
UPDATE public.service_cities SET region = 'marilia', updated_at = now() WHERE city = 'Vera Cruz' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Agudos' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Arealva' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Areiópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Balbinos' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Barra Bonita' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Bauru' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Bocaina' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Boracéia' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Botucatu' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Brotas' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Cabrália Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Dois Córregos' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Iacanga' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Igaraçu do Tietê' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Jaú' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Lençóis Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Macatuba' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Mineiros do Tietê' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Pederneiras' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Pirajuí' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Piratininga' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Pongaí' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Pratânia' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Presidente Alves' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Reginópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'São Manuel' AND state = 'SP';
UPDATE public.service_cities SET region = 'bauru-jau-botucatu', updated_at = now() WHERE city = 'Torrinha' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Adamantina' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Assis' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Bastos' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Bernardino de Campos' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Cândido Mota' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Chavantes' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Iacri' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Inúbia Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Ipaussu' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Lucélia' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Maracaí' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Osvaldo Cruz' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Ourinhos' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Palmital' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Paraguaçu Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Parapuã' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Pedrinhas Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Piraju' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Pracinha' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Queiroz' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Rinópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Sagres' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Salmourão' AND state = 'SP';
UPDATE public.service_cities SET region = 'tupa-assis-ourinhos', updated_at = now() WHERE city = 'Santa Cruz do Rio Pardo' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Alto Alegre' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Andradina' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Araçatuba' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Avanhandava' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Barbosa' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Bento de Abreu' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Bilac' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Birigui' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Buritama' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Castilho' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Clementina' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Gabriel Monteiro' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Glicério' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Guaraçaí' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Guararapes' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Ilha Solteira' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Lavínia' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Luiziânia' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Mirandópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Murutinga do Sul' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Nova Independência' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Penápolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Pereira Barreto' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Piacatu' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Rubiácea' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Santópolis do Aguapeí' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Sud Mennucci' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Suzanápolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'aracatuba-birigui', updated_at = now() WHERE city = 'Valparaíso' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Álvares Machado' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Caiabu' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Caiuá' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Dracena' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Emilianópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Euclides da Cunha Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Flórida Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Indiana' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Irapuru' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Junqueirópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Marabá Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Martinópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Mirante do Paranapanema' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Monte Castelo' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Narandiba' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Nova Guataporanga' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Ouro Verde' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Pacaembu' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Panorama' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Paulicéia' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Piquerobi' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Pirapozinho' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Presidente Bernardes' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Presidente Epitácio' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Presidente Prudente' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Presidente Venceslau' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Rancharia' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Regente Feijó' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Ribeirão dos Índios' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Rosana' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Sandovalina' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Santa Mercedes' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Santo Anastácio' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Santo Expedito' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'São João do Pau d''Alho' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Tarabai' AND state = 'SP';
UPDATE public.service_cities SET region = 'presidente-prudente', updated_at = now() WHERE city = 'Teodoro Sampaio' AND state = 'SP';
UPDATE public.service_cities SET region = 'dracena-adamantina', updated_at = now() WHERE city = 'Tupi Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Álvares Florence' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Américo de Campos' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Ariranha' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Auriflama' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Bady Bassitt' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Bálsamo' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Cardoso' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Catanduva' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Cedral' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Cosmorama' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Estrela d''Oeste' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Fernandópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Floreal' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Gastão Vidigal' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'General Salgado' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Guapiaçu' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Ibirá' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Ipiguá' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Irapuã' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Itajobi' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Jales' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'José Bonifácio' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Macaubal' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Magda' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Mendonça' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Mirassol' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Mirassolândia' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Monções' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Monte Aprazível' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Neves Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Nhandeara' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Nipoã' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Novais' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Novo Horizonte' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Onda Verde' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Paraíso' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Pindorama' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Planalto' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Poloni' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Pontes Gestal' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Sales' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Santa Adélia' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Santa Fé do Sul' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'São José do Rio Preto' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Sebastianópolis do Sul' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Tanabi' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Uchoa' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'União Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Urupês' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Valentim Gentil' AND state = 'SP';
UPDATE public.service_cities SET region = 'sao-jose-rio-preto', updated_at = now() WHERE city = 'Votuporanga' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Altair' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Altinópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Aramina' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Barretos' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Barrinha' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Batatais' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Bebedouro' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Brodowski' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Buritizal' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Cajobi' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Cajuru' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Colina' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Colômbia' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Cravinhos' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Cristais Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Dumont' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Franca' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Guaíra' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Guará' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Guaraci' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Guatapará' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Icém' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Igarapava' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Itirapuã' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Ituverava' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Jaborandi' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Jaboticabal' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Jardinópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Jeriquara' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Luís Antônio' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Miguelópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Monte Azul Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Morro Agudo' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Nuporanga' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Olímpia' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Orindiúva' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Orlândia' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Patrocínio Paulista' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Paulo de Faria' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Pedregulho' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Pirangi' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Pitangueiras' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Pontal' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Pradópolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Restinga' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Ribeirão Corrente' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Ribeirão Preto' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Rifaina' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'Sales Oliveira' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Santa Rita do Passa Quatro' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Santa Rosa de Viterbo' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Santo Antônio da Alegria' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'São Joaquim da Barra' AND state = 'SP';
UPDATE public.service_cities SET region = 'franca', updated_at = now() WHERE city = 'São José da Bela Vista' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'São Simão' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Serra Azul' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Serrana' AND state = 'SP';
UPDATE public.service_cities SET region = 'ribeirao-preto', updated_at = now() WHERE city = 'Sertãozinho' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Severínia' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Taiaçu' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Taiúva' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Terra Roxa' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Viradouro' AND state = 'SP';
UPDATE public.service_cities SET region = 'barretos-bebedouro', updated_at = now() WHERE city = 'Vista Alegre do Alto' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Américo Brasiliense' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Analândia' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Araraquara' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Boa Esperança do Sul' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Borborema' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Descalvado' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Dourado' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Gavião Peixoto' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Ibaté' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Ibitinga' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Itaju' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Itápolis' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Itirapina' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Matão' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Motuca' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Nova Europa' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Porto Ferreira' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Ribeirão Bonito' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Rincão' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Santa Lúcia' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'São Carlos' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Tabatinga' AND state = 'SP';
UPDATE public.service_cities SET region = 'araraquara-sao-carlos', updated_at = now() WHERE city = 'Trabiju' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Águas de Santa Bárbara' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Avaré' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Barão de Antonina' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Buri' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Capão Bonito' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Cerqueira César' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Coronel Macedo' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Fartura' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Guapiara' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Iaras' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Itaberá' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Itapeva' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Itaporanga' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Itararé' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Itatinga' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Pardinho' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Ribeirão Branco' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Ribeirão Grande' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Sarutaiá' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Taguaí' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Taquarituba' AND state = 'SP';
UPDATE public.service_cities SET region = 'avare-itapeva', updated_at = now() WHERE city = 'Tejupá' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Alambari' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Americana' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Angatuba' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Anhembi' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Araras' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Bofete' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Capela do Alto' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Cesário Lange' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Conchal' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Conchas' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Guareí' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Itapetininga' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Leme' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Limeira' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Pereiras' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Piracicaba' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Pirassununga' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Porangaba' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Quadra' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Rio Claro' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Santa Bárbara d''Oeste' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Tatuí' AND state = 'SP';
UPDATE public.service_cities SET region = 'borda-campinas', updated_at = now() WHERE city = 'Torre de Pedra' AND state = 'SP';
